services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: default_app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: default_app-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    container_name: default_app-db
    image: mysql:latest
    volumes:
      - ./storage/mysql:/var/lib/mysql:rw
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3406:3306"
    user: mysql
